apiVersion: v1
kind: Secret

metadata:
  name: certs

data:
{{- if .Values.global.sapcert.enabled }}
  tls.crt: {{ required ".Values.ca.cert.sap missing" .Values.ca.cert.sap | b64enc | quote }}
  ca.crt: {{ required ".Values.ca.cert.digikey missing" .Values.ca.cert.digikey | b64enc | quote }}
{{- else -}}
  ca.crt: {{ required ".Values.ca.cert.digikey missing" .Values.ca.cert.digikey | b64enc | quote }}
{{- end }}
