apiVersion: v1
kind: Secret

metadata:
  name: cron-secrets

data:
  ADMIN_USER: {{ .Values.global.users.admin.username_resolve | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.global.users.admin.password_resolve | b64enc | quote }}
  ADMIN2_USER: {{ .Values.global.users.admin2.username_resolve | b64enc | quote }}
  ADMIN2_PASSWORD: {{ .Values.global.users.admin2.password_resolve | b64enc | quote }}
