apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cbshelf
  name: {{ .Chart.Name }}-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        # is this required?
      # nodeSelector:
      #   ccloud.sap.com/nodepool: payload
      containers:
        - name: shelfback
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: cbshelf
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: cbshelfdb-config
            - configMapRef:
                name: backend-config
          volumeMounts:
            - name: vol-cbshelfapp
              mountPath: "/monsoon/cbshelf"
              #readOnly: truefvol
              {{- if eq .Values.env "production"}}
            - name: vol-cbshelfassets
              mountPath: "/app/public/assets"
              # readOnly: true
               {{- end }}
            - name: gitconfig
              mountPath: "/root"
              readOnly: true
          {{- if ne .Values.env "production"}}
            - name: shared-data
              mountPath: "/app/public/nginx"
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /app/public/assets /app/public/nginx"]
          {{- end }}
        - name: nginx
          image: keppel.eu-de-1.cloud.sap/genady/openresty:bionic-ssl-1.0
          # image:  keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/openresty/openresty:1.21.4.1-alpine-fat
          #image:  openresty/openresty:1.21.4.1-alpine-fat
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          volumeMounts:
            - name: vol-cbshelfapp
              mountPath: /monsoon/cbshelf
              #readOnly: true
             {{- if eq .Values.env "production"}}
            - name: vol-cbshelfassets
              mountPath: /app/public/assets
              # readOnly: true
              {{- end }}
            - name: nginx-conf
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: gitconfig
              mountPath: "/root"
              readOnly: true
              {{- if ne .Values.env "production"}}
            - name: shared-data
              mountPath: "/app/public"
              readOnly: true
            {{- end }}
      volumes:
        - name: vol-cbshelfapp
          persistentVolumeClaim:
            claimName: pvc-vol-cbshelfapp
        {{- if eq .Values.env "production"}}
        - name: vol-cbshelfassets
          persistentVolumeClaim:
            claimName: pvc-vol-cbshelfassets
        {{- end }}
      {{- if ne .Values.env "production"}}
        - name: shared-data
          emptyDir: {}
      {{- end }}
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: gitconfig
          secret:
            secretName: gitshelf
            defaultMode: 0400
