apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cbshelf
  name: {{ .Chart.Name }}-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        # is this required?
      # nodeSelector:
      #   ccloud.sap.com/nodepool: payload
      containers:
        - name: shelfback
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: cbshelfdb-config
            - configMapRef:
                name: backend-config
          volumeMounts:
            - name: vol-cbshelfapp
              mountPath: "/monsoon/cbshelf"
              #readOnly: truefvol
            - name: vol-cbshelfassets
              mountPath: "/app/public/assets"
              # readOnly: true
            - name: gitconfig
              mountPath: "/root"
              readOnly: true
        - name: nginx
          image:  keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/openresty/openresty
          #image:  openresty/openresty
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          volumeMounts:
            - name: vol-cbshelfapp
              mountPath: /monsoon/cbshelf
              #readOnly: true
            - name: vol-cbshelfassets
              mountPath: /app/public/assets
              # readOnly: true
            - name: nginx-conf
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: gitconfig
              mountPath: "/root"
              readOnly: true
      volumes:
        - name: vol-cbshelfapp
          persistentVolumeClaim:
            claimName: pvc-vol-cbshelfapp
        - name: vol-cbshelfassets
          persistentVolumeClaim:
            claimName: pvc-vol-cbshelfassets
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: gitconfig
          secret:
            secretName: gitshelf
            defaultMode: 0400
