apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: gitshelf
  labels:
    app: {{.Chart.Name}}
type: Opaque
stringData:
  .gitconfig: |
     [url "https://541218f8572f0516c36cf4d75075b26d68de0469@github.wdf.sap.corp/"]
     insteadOf = git://github.wdf.sap.corp/
