apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cbshelf
  name: {{ .Chart.Name }}-ingress
  annotations:
    ingress.kubernetes.io/auth-tls-secret: kube-system/ingress-cacrt
    ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    ingress.kubernetes.io/auth-tls-verify-client: "optional"
    ingress.kubernetes.io/auth-tls-verify-depth: "3"
    kubernetes.io/ingress.class: "nginx"
    {{- if contains "cloud.sap" .Values.ingress.host}}
    disco: "true"
    kubernetes.io/tls-acme: "true"
    {{- end }}
  labels:
    app: {{.Chart.Name}}
spec:

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.port }}
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingressSecret }}
