apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cbshelf
  name: cookbooks
  annotations:
    volume.beta.kubernetes.io/storage-class: cinder-default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage }}
