apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: lb
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
  selector:
     app: {{ .Chart.Name }}

