apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
namePrefix: argora-operator-
resources:
- https://github.com/sapcc/argora//config/crd
- https://raw.githubusercontent.com/sapcc/argora/refs/heads/main/config/rbac/service_account.yaml
- https://raw.githubusercontent.com/sapcc/argora/refs/heads/main/config/rbac/role.yaml
- https://raw.githubusercontent.com/sapcc/argora/refs/heads/main/config/rbac/role_binding.yaml
