---
apiVersion: v1
kind: Secret
metadata:
  name: openstack-{{ .Values.global.region }}
  namespace: garden-ccloud
type: Opaque
stringData:
  domainName: ccadmin
  tenantName: cc-gardener
  applicationCredentialID: "vault+kvv2:///secrets/{{ .Values.global.region }}/cc-gardener/application_credential_id"
  applicationCredentialSecret: "vault+kvv2:///secrets/{{ .Values.global.region }}/cc-gardener/application_credential_secret"
---
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  name: openstack-{{ .Values.global.region }}
  namespace: garden-ccloud
provider:
  type: openstack
secretRef:
  name: openstack-{{ .Values.global.region }}
---
apiVersion: v1
kind: Secret
metadata:
  name: metal-{{ .Values.global.region }}
  namespace: garden-ccloud
  annotations:
    metal.ironcore.dev/autoprovision: m-{{ required ".Values.contextSuffix missing" .Values.contextSuffix }}/metal-servers
type: Opaque
---
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  name: metal-{{ .Values.global.region }}
  namespace: garden-ccloud
provider:
  type: ironcore-metal
secretRef:
  name: metal-{{ .Values.global.region }}
