apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argora-operator.fullname" . }}-config
  labels:
    app.kubernetes.io/component: argora-operator
    app.kubernetes.io/part-of: argora-operator
  {{- include "argora-operator.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.config.configJson | quote }}
