apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "argora-operator.fullname" . }}-manager-role
  labels:
    app.kubernetes.io/component: argora-operator
    app.kubernetes.io/part-of: argora-operator
  {{- include "argora-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argora.cloud.sap
  resources:
  - updates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argora.cloud.sap
  resources:
  - updates/finalizers
  verbs:
  - update
- apiGroups:
  - argora.cloud.sap
  resources:
  - updates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - bmcs
  - bmcsecrets
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "argora-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: argora-operator
    app.kubernetes.io/part-of: argora-operator
  {{- include "argora-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "argora-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "argora-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
