apiVersion: v1
kind: Service
metadata:
  name: {{ include "argora-operator.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: argora-operator
    app.kubernetes.io/part-of: argora-operator
    control-plane: controller-manager
  {{- include "argora-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app.kubernetes.io/name: argora
    control-plane: controller-manager
    {{- include "argora-operator.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.metricsService.ports | toYaml | nindent 2 }}
