apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argora-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: argora-operator
    app.kubernetes.io/part-of: argora-operator
  {{- include "argora-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
