{{- if .Values.updates -}}
kind: Namespace
apiVersion: v1
metadata:
  name: argora-system
{{- range $name, $clusters := .Values.updates }}
---
apiVersion: argora.cloud.sap/v1alpha1
kind: Update
metadata:
  name: {{ $name }}
  namespace: argora-system
spec:
  clusters:
{{ toYaml $clusters | nindent 2 }}
{{- end }}
{{- end }}
