apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perses-content-pvc
  namespace: perses  # Adjust namespace as needed
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Adjust size as needed