---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perses-content-pvc
  namespace: perses-playground  # Adjust namespace as needed
  annotations:
    "helm.sh/hook-weight": "0"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Adjust size as needed

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: perses-content-sync
  namespace: perses-playground  # Adjust namespace as needed
  annotations:
    "helm.sh/hook-weight": "1"
spec:
  schedule: "*/2 * * * *"  # Every 2 minutes
  concurrencyPolicy: Replace  # Replace running job if it's still running
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: content-sync
            image: keppel.eu-de-1.cloud.sap/ccloud-gcr-mirror/go-containerregistry/crane:debug
            command: ["/busybox/sh"]
            args:
              - -c
              - |
                set -e
                echo "Starting content sync at $(date)"
                
                # Create temp directory for extraction
                TEMP_DIR="/tmp/perses-extract"
                mkdir -p "$TEMP_DIR"
                
                # Pull and extract the OCI artifact using crane
                echo "Pulling image: keppel.eu-de-1.cloud.sap/ccloud/perses-dashboards:v0.1.0"
                crane export keppel.eu-de-1.cloud.sap/ccloud/perses-dashboards:v0.1.0 - | tar -xf - -C "$TEMP_DIR"
                
                # Clear existing content in PVC (optional - remove if you want to keep old files)
                echo "Clearing existing content..."
                rm -rf /etc/perses/provisioning/* || true
                
                # Copy extracted content to PVC
                echo "Copying content to PVC..."
                cp -r "$TEMP_DIR/perses-content"/* /etc/perses/provisioning/            
                
                # List copied files for verification
                echo "Content successfully synced. Files in PVC:"
                find /etc/perses/provisioning -type f -name "*.json" | head -10
                echo "Total JSON files: $(find /etc/perses/provisioning -name "*.json" | wc -l)"
                
                # Cleanup
                rm -rf "$TEMP_DIR"
                echo "Content sync completed at $(date)"
            
            volumeMounts:
            - name: perses-content-volume
              mountPath: /etc/perses/provisioning
            
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          
          volumes:
          - name: perses-content-volume
            persistentVolumeClaim:
              claimName: perses-content-pvc