apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perses-content-pvc
  namespace: perses  # Adjust namespace as needed
  annotations:
    "helm.sh/hook-weight": "0"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Adjust size as needed