apiVersion: v2
description: Helm chart for Cerebro infrastructure
name: cerebro
version: 0.1.4
maintainers:
  - name: Arno Uhlig (auhlig)
  - name: Malte Viering (umswmayj)
  - name: Max Hofmann (maxhof42)
dependencies:
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.2.0
