apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-harvest.fullname" . }}
  labels:
    {{- include "netapp-harvest.labels" . | nindent 4 }}
type: Opaque
data:
  netappUsername: {{ required ".Values.global.netapp_exporter_user" .Values.global.netapp_exporter_user | b64enc | quote }}
  netappPassword: {{ required ".Values.global.netapp_exporter_password" .Values.global.netapp_exporter_password | b64enc | quote }}
  netboxToken: {{ required ".Values.global.netbox_api_token" .Values.global.netbox_api_token | b64enc | quote }}
  credentials.yaml: {{ include (print .Template.BasePath "/_credentials.yaml.tpl") . | b64enc }}
  {{- if eq .Values.global.region "qa-de-1" }}
  netboxHost: {{ required ".Values.global.netbox_host_staging" .Values.global.netbox_host_staging | b64enc | quote }}
  {{- else }}
  netboxHost: {{ required ".Values.global.netbox_host" .Values.global.netbox_host | b64enc | quote }}
  {{- end }}
