global:
  registry: myRegistry
  dbPassword: topSecret
  dockerHubMirror: myRegistry/dockerhub
  dockerHubMirrorAlternateRegion: myRegistry/dockerhubalternate
  glance_service_password: secret
  availability_zones:
    - foo
    - bar
  domain_seeds:
    customer_domains: [bar, foo, baz]
    customer_domains_without_support_projects: [baz]
    
imageVersion: rocky

rabbitmq_notifications:
  users:
    default:
      password: secret!

mariadb:
  root_password: rootroot
  backup_v2:
    swift:
      password: topSecret
  users:
    glance:
      name: glance
      password: password
    backup:
      name: backup
      password:  password

rabbitmq:
  users:
    admin:
      password: adminadmin
    default:
      password: defaultdefault
  metrics:
    password: metricsmetrics

audit:
  central_service:
    user: glance
    password: password

swift:
  enabled: false
