apiVersion: v2
name: cc-gardener
description: Converged Cloud Gardener setup based on gardener-operator
type: application
version: 0.4.0
appVersion: "v1.108.1"
home: https://github.com/gardener/gardener
dependencies:
- name: operator
  repository: oci://europe-docker.pkg.dev/gardener-project/releases/charts/gardener
  version: v1.108.1
- name: owner-info
  repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
  version: 0.2.0
