apiVersion: v1
kind: ConfigMap

metadata:
  name: hubcopter-html

data:
  index.html: |
    <!DOCTYPE html>
    <meta charset="utf-8">
    <title>Hubcopter 🚁💨</title>
    <main>
      <h1>Hubcopter 🚁💨</h1>
      <ul>
{{- range $instance, $description := required ".Values.hubcopter.instances is missing" .Values.hubcopter.instances }}
        <li><a href="/{{ $instance }}/">{{ $description }}</a></li>
{{- end }}
      </ul>
    </main>
