kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: hubcopter-api
  annotations:
    disco: "true"
    ingress.kubernetes.io/auth-url: "https://auth-internal.eu-de-2.{{ $.Values.global.tld }}/oauth2/auth"
    ingress.kubernetes.io/auth-signin: "https://auth-internal.eu-de-2.{{ $.Values.global.tld }}/oauth2/start"
    ingress.kubernetes.io/auth-request-redirect: $escaped_request_uri
    ingress.kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/tls-acme: "true"

spec:
  tls:
    - secretName: tls-hubcopter-api
      hosts: [ 'hubcopter.global.{{ .Values.global.tld }}' ]
  rules:
    - host: 'hubcopter.global.{{ .Values.global.tld }}'
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: hubcopter-html
                port:
                  number: 80
{{- range $key, $value := required ".Values.hubcopter.instances is missing" .Values.hubcopter.instances }}
          - path: /{{ $key }}/(.*)
            pathType: Prefix
            backend:
              service:
                name: hubcopter-api-{{ $key }}
                port:
                  number: 8080
{{- end }}
