---
kind: Service
apiVersion: v1

metadata:
  name: glas-api

spec:
  selector:
    name: glas-api
  ports:
    - port: 8081

---
kind: Service
apiVersion: v1

metadata:
  name: hubcopter-html

spec:
  selector:
    name: hubcopter-html
  ports:
    - port: 80

{{- range $key, $value := (required ".Values.hubcopter.instances is missing" .Values.hubcopter.instances) }}
---
kind: Service
apiVersion: v1

metadata:
  name: hubcopter-api-{{ $key }}

spec:
  selector:
    name: hubcopter-api-{{ $key }}
  ports:
    - port: 8080
{{- end }}
