apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ include "prometheus-gardener.fullname" . }}-alertmanager-{{ .Values.name }}
  labels:
    alertmanager: {{ .Values.name }}
    component: alertmanager
    role: monitoring
  {{- include "prometheus-gardener.labels" . | nindent 4 }}
spec:
  alertmanagerConfigMatcherStrategy:
    type: None
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector:
    matchLabels:
      alertmanager: {{ .Values.name }}
  externalUrl: https://sap.com
  forceEnableClusterMode: true
  imagePullPolicy: IfNotPresent
  logLevel: info
  podMetadata:
    labels:
      alertmanager: {{ .Values.name }}
      component: alertmanager
      networking.gardener.cloud/to-dns: allowed
      networking.gardener.cloud/to-private-networks: allowed
      networking.gardener.cloud/to-public-networks: allowed
      networking.resources.gardener.cloud/to-alertmanager-operated-tcp-9094: allowed
      networking.resources.gardener.cloud/to-alertmanager-operated-udp-9094: allowed
      observability.gardener.cloud/app: {{ include "prometheus-gardener.fullname" . }}-alertmanager-{{ .Values.name }}
      role: monitoring
  priorityClassName: gardener-garden-system-100
  replicas: 1
  resources:
    requests:
      cpu: 5m
      memory: 20Mi
  securityContext:
    runAsUser: 0
  storage:
    volumeClaimTemplate:
      metadata:
        name: alertmanager-db
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
status:
  availableReplicas: 0
  paused: false
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
