apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prometheus-gardener.fullname" . }}-prometheus-{{ .Values.name }}
  labels:
    app: prometheus
    name: {{ .Values.name }}
    role: monitoring
  {{- include "prometheus-gardener.labels" . | nindent 4 }}
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: {{ include "prometheus-gardener.fullname" . }}-prometheus-{{ .Values.name }}
  namespace: '{{ .Release.Namespace }}'
