apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-gardener.fullname" . }}-prometheus-{{ .Values.name }}
  labels:
    app: prometheus
    name: {{ .Values.name }}
    role: monitoring
  {{- include "prometheus-gardener.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.prometheus.serviceAccount.annotations | nindent 4 }}
