apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "prometheus-gardener.fullname" . }}-prometheus-{{ .Values.prometheusName }}
  labels:
    app: prometheus
    name: {{ .Values.prometheusName }}
    observability.gardener.cloud/app: {{ include "prometheus-gardener.fullname" . }}-prometheus-{{ .Values.prometheusName }}
    role: monitoring
  {{- include "prometheus-gardener.labels" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: prometheus
      controlledValues: RequestsOnly
      minAllowed:
        memory: 100M
    - containerName: config-reloader
      mode: "Off"
  targetRef:
    apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    name: {{ include "prometheus-gardener.fullname" . }}-prometheus-{{ .Values.prometheusName }}
  updatePolicy:
    updateMode: Auto
status: {}
