apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-gardener.fullname" . }}-prometheus-{{ .Values.prometheusName }}
  labels:
    app: prometheus
    name: {{ .Values.prometheusName }}
    role: monitoring
  {{- include "prometheus-gardener.labels" . | nindent 4 }}
data:
  prometheus.yaml: {{ required "prometheusAdditionalScrapeConfigs.prometheusYaml is required" .Values.prometheusAdditionalScrapeConfigs.prometheusYaml | b64enc
    | quote }}
type: Opaque
