apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-gardener.fullname" . }}-prometheus-{{ .Values.prometheusName }}
  labels:
    app: prometheus
    name: {{ .Values.prometheusName }}
    role: monitoring
  {{- include "prometheus-gardener.labels" . | nindent 4 }}
  annotations:
    networking.resources.gardener.cloud/from-all-seed-scrape-targets-allowed-ports: '[{"protocol":"TCP","port":9090}]'
    networking.resources.gardener.cloud/namespace-selectors: '[{"matchLabels":{"gardener.cloud/role":"shoot"}}]'
spec:
  type: {{ .Values.prometheus.type }}
  selector:
    prometheus: {{ include "prometheus-gardener.fullname" . }}-prometheus-{{ .Values.prometheusName }}
    component: prometheus
    role: monitoring
  ports:
  {{- .Values.prometheus.ports | toYaml | nindent 2 }}
