apiVersion: v2
name: argora-operator
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
dependencies:
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: '>= 0.0.0'
  - name: argora-operator
    repository: oci://ghcr.io/sapcc/charts/argora
    version: 0.0.0-0e22732
    alias: argora-operator-core
