owner-info:
  support-group: containers
  helm-chart-url: https://github.com/gardener/etcd-backup-restore

clusterName: ""
namespace: "kube-system"

deployment:
  enable: true
  replicas: 1
  container:
    image:
      repository: keppel.global.cloud.sap/ccloud-europe-docker-pkg-dev-mirror/gardener-project/releases/gardener/etcdbrctl
      tag: v0.38.0
    resources:
      limits:
        cpu: 100m
        memory: 1Gi
      requests:
        cpu: 23m
        memory: 128Mi
    securityContext:
      runAsUser: 0
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: etcd-kcp

configmap:
  enable: true

secret:
  enable: true

service:
  enable: true

serviceAccount:
  enable: true

clusterRole:
  enable: true

clusterRoleBinding:
  enable: true

lease:
  enable: true

awsCredentials:
  accessKeyID: ""
  secretAccessKey: ""
  region: ""
