global:
  keystoneNamespace: keystone
  region: xx-yy-1
  tld: example.org
  registry: registry.example.com
  quayIoMirror: registry.example.com/quayio

limes:
  image_tag: '19700101000000'
  passwords:
    ccloud:
      os_password: abc
