controllerManager:
  manager:
    args:
      - --mac-prefixes-file=/etc/macdb/macdb.yaml
      - --probe-image=keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/ironcore-dev/metalprobe:latest
      - --probe-os-image=ghcr.io/ironcore-dev/os-images/gardenlinux:1443.3
      - --insecure=false
      - --registry-url=http://[2a10:afc0:e013:d002::]:30010
      - --manager-namespace=metal-operator-system
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    env:
      enableWebhooks: "false"
      kubernetesServiceHost: apiserver-url
    image:
      repository: controller
      tag: b705a57f5ee159073141f999d02201023a794d55
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  podSecurityContext:
    runAsNonRoot: true
  replicas: 1
kubernetesClusterDomain: cluster.local
metalRegistryService:
  ports:
    - nodePort: 30010
      port: 80
      protocol: TCP
      targetPort: 10000
  type: NodePort
fullnameOverride: metal-operator
remote:
  ca: ""
macdb: {}
