global:
  linkerd_requested: true

campfire:
  image_tag: null # defined in values file
  cpu_request: 20m
  memory_limit: 64Mi
  passwords:
    ccloud:
      os_password: null # defined in values file
