{{- if .Values.blockrbdpool.enabled }}
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: {{ .Values.blockrbdpool.name }}
spec:
  {{- if .Values.blockrbdpool.pools.failureDomain }}
  failureDomain: {{ .Values.blockrbdpool.pools.failureDomain | default "host"  }}
  {{- end }}
  replicated:
    size: {{ .Values.blockrbdpool.pools.size | default 3 }}
    {{- if .Values.blockrbdpool.pools.replicasPerFailureDomain }}
    replicasPerFailureDomain: {{ .Values.blockrbdpool.pools.replicasPerFailureDomain | default 1 }}
    {{- end }}
    {{- if .Values.blockrbdpool.pools.subFailureDomain }}
    subFailureDomain: {{ .Values.blockrbdpool.pools.subFailureDomain | default "host" }}
    {{- end }}
  {{- if .Values.blockrbdpool.pools.crushRoot }}
  crushRoot: {{ .Values.blockrbdpool.pools.crushRoot | default "default" }} 
  {{- end }}
  deviceClass: nvme
  application: rbd
  parameters:
    pg_num: "1024"
    pgp_num: "1024"
    nodelete: {{ $.Values.pool.nodelete | quote }}
    nosizechange: {{ $.Values.pool.nosizechange | quote }}
{{- end }}
