{{- if .Values.objectstore.prysm.rgwMetrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.objectstore.name }}-ext-rgw-exporter
  labels:
    app: {{ .Values.objectstore.name }}-ext-rgw-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.objectstore.name }}-ext-rgw-exporter
  template:
{{- $secretName := printf "rook-ceph-object-user-%s-%s" (.Values.objectstore.prysm.rgwMetrics.user.store | default .Values.objectstore.name) .Values.objectstore.prysm.rgwMetrics.user.name }}
    metadata:
      annotations:
        checksum/secret: {{ with (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
          {{- if .data -}}
            {{- .data | toJson | sha256sum -}}
          {{- else -}}
{{ printf "no-data-%s-%s" .Release.Namespace $secretName | quote }}
          {{- end -}}
        {{- else -}}
{{ printf "no-secret-%s-%s" .Release.Namespace $secretName | quote }}
        {{- end }}
      labels:
        app: {{ .Values.objectstore.name }}-ext-rgw-exporter
    spec:
      serviceAccountName: rgw-exporter-init-container-service-account
      initContainers:
      - name: wait-for-secret
        image: {{ .Values.objectstore.prysm.initContainer.repository.image }}:{{ .Values.objectstore.prysm.initContainer.repository.tag }}
        imagePullPolicy: {{ .Values.objectstore.prysm.initContainer.repository.pullPolicy }}
        command:
          - sh
          - "-c"
          - |
              # Wait for the secret to be available
              echo "Waiting for secret to be available..."
              until kubectl -n {{ .Release.Namespace }} get secret -l rook_object_store={{ .Values.objectstore.prysm.rgwMetrics.user.store }},user={{ .Values.objectstore.prysm.rgwMetrics.user.name }} -o jsonpath='{.items[0].metadata.name}'; do
                sleep 5
              done
              echo "Secret is now available!"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
      containers:
      - name: prysm
        image: {{ .Values.objectstore.prysm.repository.image }}:{{ .Values.objectstore.prysm.repository.tag }}
        imagePullPolicy: {{ .Values.objectstore.prysm.repository.pullPolicy }}
        args:
        - "remote-producer"
        - "radosgw-usage"
        - '--rgw-cluster-id={{ .Values.objectstore.name }}'
        - '--prometheus=true'
        - '-v=info'
        env:
        - name: ADMIN_URL
          value: {{ .Values.objectstore.prysm.rgwAdminUrl | quote }}
        - name: INTERVAL
          value: {{ .Values.objectstore.prysm.rgwMetrics.interval | quote }}
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
# see https://github.com/rook/rook/blob/e23e921f2844f9fb9fc46f04dfdf5302ee5df49a/pkg/operator/ceph/object/user/controller.go#L514
              name: {{ $secretName }}
              key: AccessKey
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ $secretName }}
              key: SecretKey
        ports:
        - containerPort: 8080
          name: metrics
{{- end }}
