apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-recommender
  template:
    metadata:
      labels:
        app: vpa-recommender
      annotations:
        prometheus.io/scrape: "true"
        {{- if .Values.additionalPodAnnotations }}
        {{- toYaml .Values.additionalPodAnnotations | nindent 8 -}}
        {{ end }}
    spec:
      serviceAccountName: vpa-recommender
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
        - name: recommender
          image: {{ include "recommender.image" . }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.recommender.image.pullPolicy }}
          args:
            - --recommender-interval={{ required ".Values.recommender.interval missing" .Values.recommender.interval }}
            {{- if .Values.recommender.prometheusAddress }}
            - --storage=prometheus
            - --prometheus-address={{.Values.recommender.prometheusAddress }}
            {{- end }}
            {{- if .Values.recommender.prometheusCadvisorJobName }}
            - --prometheus-cadvisor-job-name={{.Values.recommender.prometheusCadvisorJobName}}
            {{- end }}
          resources:
            limits:
              cpu: 200m
              memory: 1000Mi
            requests:
              cpu: 50m
              memory: 500Mi
          ports:
            - name: metrics
              containerPort: 8942
