apiVersion: v1
kind: ConfigMap

metadata:
  name: limes-liquids

data:
  policy.json: |
    {
      "readwrite": "role:cloud_resource_admin or (user_name:limes and user_domain_name:Default)",
      "readonly": "role:cloud_resource_viewer or rule:readwrite",
      "mail:send": "rule:readonly"
    }
