apiVersion: v1
kind: Secret
metadata:
  name: campfire-secret
data:
  os_password: {{ required ".Values.campfire.passwords.ccloud.os_password" .Values.campfire.passwords.ccloud.os_password | b64enc }}
