harvest:
  image:
    repository: rahulguptajss/harvest
    pullPolicy: IfNotPresent
    tag: 22.11.1-1
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi
  loglevel: 2
  pollerCount: 2
  promPort: 13000
    
netappsd:
  image:
    repository: netappsd
    tag: master-2eb9d5a-20230127193456
  resources:
    limits:
      cpu: 400m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/targets: "infra-collector"

replicaCount: 1
