owner-info:
  support-group: observability
  maintainers:
    - Tommy Sauer
    - Richard Tief
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/thanos-metal

thanos:
  name: metal
  deployWholeThanos: false
  ingress:
    enabled: true
    hosts:
      - thanos-metal
      - metrics.metal
  grpcIngress:
    enabled: true
    hosts:
      - thanos-metal
  queryDiscovery: true
  clusterDomain: kubernetes

  alerts:
    prometheus: kubernetes
