# The CRDs required can be found in the crds folder and are only applied on helm install.
# As a convenience when using helm upgrade they are also installed via templates if installCRDs is true.
# WARNING: Delete with care as removing of the CRDs will remove all instances of it.
installCRDs: false

image:
  # Configure the registry for all VPA images.
  # Default: k8s.gcr.io
  # In Converged Cloud we use our in-house image registry.
  registry: keppel.global.cloud.sap/ccloud-k8sgcr-mirror

# Additional annotations applied to each pod (recommender, admission, updater).
additionalPodAnnotations:
  prometheus.io/targets: "kubernetes"

# The recommender is always enabled.
recommender:
  image:
    # The full image will be $registry/$repository:$tag.
    registry: keppel.global.cloud.sap/ccloud-k8sgcr-mirror
    repository: autoscaling/vpa-recommender
    pullPolicy: IfNotPresent

  # How often metrics should be fetched.
  interval: 5m

  # Where to reach for Prometheus metrics.
  prometheusAddress: https://prometheus-kubernetes.kube-monitoring.svc

  # Name of the prometheus job name which scrapes the cAdvisor metrics.
  prometheusCadvisorJobName: kubernetes-cadvisors

admission:
  enabled: true
  image:
    # The full image will be $registry/$repository:$tag.
    repository: autoscaling/vpa-admission-controller
    pullPolicy: IfNotPresent

updater:
  enabled: true
  image:
    # The full image will be $registry/$repository:$tag.
    registry: keppel.global.cloud.sap/ccloud-k8sgcr-mirror
    repository: autoscaling/vpa-updater
    pullPolicy: IfNotPresent
