---
apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: unbound-openstack-alerts
  labels:
    app: unbound
    tier: os
    type: alerting-rules
    prometheus: openstack

spec:
  groups:
  - name: unbound.alerts
    rules:
    - alert: DnsUnboundManySERVFAIL
      expr: sum(delta(unbound_answer_rcodes_total{rcode="SERVFAIL"}[1h])) BY (region, app) > 500000
      for: 60m
      labels:
        context: unbound
        dashboard: dns-unbound-and-f5-performance
        meta: {{` '{{ $labels.app }}' `}}
        service: unbound
        severity: info
        support_group: network-api
        tier: os
        playbook: 'docs/devops/alert/designate'
      annotations:
        description: {{` 'Recursor {{ $labels.app }} returns lots of SERVFAIL responses in {{ $labels.region }} region.' `}}
        summary: {{` '{{ $labels.app }} returned a lot of SERVFAIL responses in the last hour. Check the logs.' `}}

    - alert: DnsUnbound1Down
      expr: absent(unbound_up{app="unbound1"}) == 1 or unbound_up{app="unbound1"} != 1
      for: 30m
      labels:
        context: unbound
        dashboard: dns-unbound-and-f5-performance
        meta: unbound1
        service: unbound
        severity: warning
        support_group: network-api
        tier: os
        playbook: 'docs/devops/alert/designate/#test_unbound_endpoint'
      annotations:
        description: 'DNS Unbound1 recursor is down.'
        summary: DNS Unbound1 recursor is down. DNS resolution might be handled by another region.

    - alert: DnsUnbound2Down
      expr: absent(unbound_up{app="unbound2"}) == 1 or unbound_up{app="unbound2"} != 1
      for: 30m
      labels:
        context: unbound
        dashboard: dns-unbound-and-f5-performance
        meta: unbound2
        service: unbound
        severity: warning
        support_group: network-api
        tier: os
        playbook: 'docs/devops/alert/designate/#test_unbound_endpoint'
      annotations:
        description: 'DNS Unbound2 recursor is down.'
        summary: DNS Unbound2 recursor is down. DNS resolution might be handled by another region.

---
apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: unbound-kubernetes-alerts
  labels:
    app: unbound
    tier: os
    type: alerting-rules
    prometheus: kubernetes

spec:
  groups:
  - name: unbound.alerts
    rules:
    - alert: DnsUnboundEndpointNotAvailable
      expr: max(kube_endpoint_address{namespace="dns-recursor"}) BY (region,endpoint) < 1
      for: 15m
      labels:
        context: unbound
        dashboard: dns-unbound-and-f5-performance
        meta: {{` '{{ $labels.endpoint }}' `}}
        service: unbound
        severity: warning
        support_group: network-api
        tier: os
        playbook: 'docs/devops/alert/designate/#test_unbound_endpoint'
      annotations:
        description: {{` 'DNS Unbound endpoint {{ $labels.endpoint }} not available in {{ $labels.region }} region.' `}}
        summary: {{` 'DNS Unbound endpoint {{ $labels.endpoint }} is not available. DNS resolution might be handled by another region.' `}}
