{{- if .Values.ingress.enabled -}}
{{- $values := .Values -}}

{{- range $i, $statsd := .Values.statsd -}}
{{ if ne $i 0 }}---{{ end }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  fullName: {{ printf "%s" $statsd.fullName }}
  labels:
{{- include "statsd-exporter.labels" . | nindent 4 }}
    name: {{ printf "%s" $statsd.name }}
  annotations:
    kubernetes.io/tls-acme: {{ required "$values.ingress.tls missing" $values.ingress.tls | quote }}
    disco: {{ required "$values.ingress.disco missing" $values.ingress.disco | quote }}
spec:
  tls:
     - secretName: {{ printf "%s" $statsd.fullName }}
{{ if $values.global.clusterType }}
       hosts: [{{ printf "%s" $statsd.name }}.{{ $values.global.clusterType }}.{{ $values.global.region }}.{{ $values.global.tld }}]
{{ else }}
       hosts: [{{ printf "%s" $statsd.name }}.{{ $values.global.region }}.{{ $values.global.tld }}]
{{ end }}
  rules:
{{ if $values.global.clusterType }}
    - host: {{ printf "%s" $statsd.name }}.{{ $values.global.clusterType }}.{{ $values.global.region }}.{{ $values.global.tld }}
{{ else }}
    - host: {{ printf "%s" $statsd.name }}.{{ $values.global.region }}.{{ $values.global.tld }}
{{ end }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              fullName: {{ printf "%s" $statsd.fullName }}
              port:
                number: {{ $values.metrics.port }}

{{- end }}
---
{{ end -}}