{{- range $i, $exporter := .Values.exporters -}}
{{- if $exporter.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "statsd-exporter.fullName" $exporter.name }}
  namespace: {{ required ".Values.namespace variable missing" $.Values.nameSpace }}
  labels:
    {{- include "statsd-exporter.labels" $exporter.name | nindent 4 }}
  annotations:
    kubernetes.io/tls-acme: {{ required ".Values.ingress.tls variable missing" $.Values.ingress.tls | quote }}
    disco: {{ required ".Values.ingress.disco variable missing" $.Values.ingress.disco | quote }}
spec:
  tls:
     - secretName: {{ include "statsd-exporter.fullName" $exporter.name }}
{{- if $.Values.global.clusterType }}
       hosts: [{{ include "statsd-exporter.fullName" $exporter.name }}.{{ $.Values.global.clusterType}}.{{ $.Values.global.region }}.{{ $.Values.global.tld }}]
{{- else }}
       hosts: []{{ include "statsd-exporter.fullName" $exporter.name }}.{{ $.Values.global.region }}.{{ $.Values.global.tld }}]
{{ end }}
  rules:
{{- if $.Values.global.clusterType }}
    - host: {{ include "statsd-exporter.fullName" $exporter.name }}.{{ $.Values.global.clusterType}}.{{ $.Values.global.region }}.{{ $.Values.global.tld }}
{{- else }}
       host: {{ include "statsd-exporter.fullName" $exporter.name }}.{{ $.Values.global.region }}.{{ $.Values.global.tld }}
{{ end }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              fullName: {{ include "statsd-exporter.fullName" $exporter.name }}
              port:
                number: {{ required ".Values.exporters.metricsPort variable missing" $exporter.metricsPort }}
---
{{ end -}}
{{ end -}}