{{- $values := .Values -}}

{{- range $i, $statsd := .Values.statsd -}}
{{ if ne $i 0 }}---{{ end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s" $statsd.fullName }}
  labels:
    app: {{ printf "%s" $statsd.name }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $values.nameSpace }}
  selector:
    matchLabels:
      app: {{ printf "%s" $statsd.name }}

  ports:
    - name: metrics
      port: {{ $vaules.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- if $values.statsd.tcpPort }}
    - name: statsd-tcp
      port: {{ $values.statsd.tcpPort }}
      targetPort: statsd-tcp
      protocol: TCP
{{- end }}
{{- if $values.statsd.udpPort }}
    - name: statsd-udp
      port: {{ $values.statsd.udpPort }}
      targetPort: statsd-udp
      protocol: UDP
{{- end }}
---
{{ end -}}
