{{- range $i, $exporter := .Values.exporters -}}
{{- if $exporter.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "statsd-exporter.fullName" $exporter.name }}
  namespace: {{ required ".Values.namespace variable missing" $.Values.nameSpace }}
  labels:
    {{- include "statsd-exporter.labels" $exporter.name | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Values.nameSpace }}
  selector:
    matchLabels:
      {{- include "statsd-exporter.labels" $exporter.name | nindent 6 }}
  ports:
    - name: metrics
      port: {{ required ".Values.exporters.metricsPort variable missing" $exporter.metricsPort }}
      targetPort: metrics
      protocol: TCP
    - name: statsd-tcp
      port: {{ required ".Values.exporter.tcpPort variable missing" $exporter.tcpPort }}
      targetPort: statsd-tcp
      protocol: TCP
    - name: statsd-udp
      port: {{ required ".Values.exporter.udpPort variable missing" $exporter.udpPort }}
      targetPort: statsd-udp
      protocol: UDP
---
{{ end -}}
{{ end -}}
