replicaCount: 1

isDebug: false

owner-info:
  helm-chart-url: 'https://github.com/sapcc/helm-charts/tree/master/global/pulsar'
  maintainers:
    - Tilo Geissler
    - Bassel Zeidan
  support-group: observability
  service: pulsar

image:
  repository: keppel.eu-de-1.cloud.sap/ccloud/pulsar
  tag: v1.1.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ingress.class: nginx-internet
    kubernetes.io/ingress.class: nginx-internet

  hosts: []

config:
  slack:
    # botToken:
    # botID:
    # accessToken:
    # verificationToken:
    # channelMessageHistoryScanCount:
    authorizedUserGroupNames: []
    channelIdList: []

  pagerduty:
    # defaultEmail:
    # authToken:
    serviceIdList: []
