---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argora
  labels:
    app: argora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argora
  template:
    metadata:
      labels:
        app: argora
        networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-private-networks: allowed
    spec:
      serviceAccountName: default
      containers:
        - name: argora
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - --controllers={{ .Values.controllers }}
            - --metrics-bind-address={{ .Values.metrics.bindAddress }}
          envFrom:
            - secretRef:
                name: argora
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: remote-kubeconfig
            mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            readOnly: true
      volumes:
      - name: remote-kubeconfig
        secret:
          secretName: argora-remote-kubeconfig
          items:
          - key: token
            path: token
          - key: bundle.crt
            path: ca.crt
