apiVersion: v1
kind: Secret
metadata:
  name: argora
type: Opaque
data:
  NETBOX_TOKEN: {{ .Values.netbox.token | b64enc }}
  NETBOX_URL: {{ .Values.netbox.url | b64enc }}
  BMC_USER: {{ .Values.bmc.username | b64enc }}
  BMC_PASS: {{ .Values.bmc.password | b64enc }}
  IRONCORE_REGION: {{ .Values.ironcore.region | b64enc }}
  IRONCORE_TYPES: {{ .Values.ironcore.clusterTypes | b64enc }}
  KUBERNETES_SERVICE_HOST: {{ .Values.env.kubernetesServiceHost | b64enc }}
