apiVersion: v1
kind: ConfigMap

metadata:
  name: castellum

data:
  {{- if .Values.castellum.asset_managers | has "nfs-shares" }}
  netapp-scout.yaml: |
    http:
      listen_address: ':8080'
    prometheus:
      {{- if .Values.castellum.prometheus_infra }}
      url:  "https://metrics.metal.{{ .Values.global.region }}.cloud.sap"
      cert: /etc/castellum-certs/prometheus-infra.cert.pem
      key:  /etc/castellum-certs/prometheus-infra.key.pem
      {{- else }}
      url:  http://prometheus-storage.infra-monitoring.svc:9090
      {{- end }}
  {{- end }}

  policy.yaml: |
{{ .Files.Get "files/policy.yaml" | indent 4 }}
