{{- $cdomains := .Values.global.domain_seeds.customer_domains | required "missing value for .Values.global.domain_seeds.customer_domains" -}}
{{- $domains := concat (list "ccadmin") $cdomains -}}
{{- $internalDomainsWithoutAllProjects := list "btp_fp" "kyma" "ora"}}

apiVersion: "openstack.stable.sap.cc/v1"
kind: OpenstackSeed
metadata:
  name: keppel-support-seed

spec:
  requires:
  - keppel/keppel-seed
  {{- range $domains }}
  - monsoon3/domain-{{replace "_" "-" .}}-seed
  {{- end }}

  domains:
    {{- range $domains }}
    - name: {{ . | lower }}
      groups:
      - name: {{ contains "iaas-" . | ternary . ( upper . ) }}_API_SUPPORT
        role_assignments:
        {{- if not (or (contains "iaas-" .) (has . $internalDomainsWithoutAllProjects)) }}
        - project: api_support
          role: registry_admin
        {{- if eq . "ccadmin" }}
        - project: api_tools
          role: registry_admin
        {{- end }}
        {{- end }}
        # Inherit read-only role within domain
        - domain: {{ . | lower }}
          role: registry_viewer
          inherited: true
      - name: {{ contains "iaas-" . | ternary . ( upper . ) }}_STORAGE_SUPPORT
        role_assignments:
        {{- if not (or (contains "iaas-" .) (has . $internalDomainsWithoutAllProjects)) }}
        - project: storage_support
          role: registry_admin
        {{- if eq . "ccadmin" }}
        - project: storage_tools
          role: registry_admin
        {{- end }}
        {{- end }}
        # Inherit read-only role within domain
        - domain: {{ . | lower }}
          role: registry_viewer
          inherited: true
      - name: {{ contains "iaas-" . | ternary . ( upper . ) }}_SERVICE_DESK
        role_assignments:
        {{- if not (or (contains "iaas-" .) (has . $internalDomainsWithoutAllProjects)) }}
        - project: service_desk
          role: registry_admin
        {{- end }}
        # Inherit read-only role within domain
        - domain: {{ . | lower }}
          role: registry_viewer
          inherited: true
    {{- end }}
