name: pgbackup
#
# NOTE: When upgrading please note the following changes:
#
# 1.2.0
# - Added `.Values.reloader.enabled` to control consumption of
#   `stakater/Reloader` annotations on referenced Secrets and CMs.
#
version: 1.2.20 # this version number is SemVer as it gets used to auto bump
apiVersion: v2
description: PostgreSQL backup/restore pod
appVersion: "v0.10.0-175-g484d2f4" # of https://github.com/sapcc/backup-tools
