apiVersion: v1
kind: ConfigMap

metadata:
  name: campfire

data:
  policy.json: |
    {
      "readwrite": "(user_name:limes or user_name: dashboard) and user_domain_name:Default",
      "mail:send": "rule:readwrite"
    }
