apiVersion: v1
kind: ConfigMap

metadata:
  name: campfire

data:
  policy.json: |
    {
      "match_limes_user": "user_name:limes and user_domain_name:Default",
      "match_elektra_user": "user_name:dashboard and user_domain_name:Default"
      "mail:send": "rule:match_limes_user or rule:match_elektra_user"
    }
