{{- $tld    := $.Values.global.tld    | required "missing value for .Values.global.tld"    -}}
{{- $region := $.Values.global.region | required "missing value for .Values.global.region" -}}

{{- $domain := printf "%s.%s.%s" "limes-campfire" $region $tld -}}
{{- if eq .Release.Namespace "limes-global" -}}
  {{- $domain = printf "%s.global.%s" (contains "qa" $region | ternary "limes-campfire-qa" "limes-campfire") $tld -}}
{{- end -}}

kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: campfire
  annotations:
    kubernetes.io/tls-acme: "true"
    disco: "true"
    {{- if and $.Values.global.linkerd_enabled $.Values.global.linkerd_requested }}
    ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    {{- end }}

spec:
  tls:
    - secretName: tls-campfire
      hosts: [ {{ $domain }} ]
  rules:
    - host: {{ $domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: campfire
                port:
                  number: 80
