{{- $vbase  := .Values.global.vaultBaseURL | required "missing value for .Values.global.vaultBaseURL" -}}
{{- $region := .Values.global.region       | required "missing value for .Values.global.region"       -}}

apiVersion: v1
kind: Secret
metadata:
  name: campfire-secret
data:
  os_password:     {{ printf "%s/%s/%s/keystone-user/service/password"  $vbase $region .Release.Namespace | b64enc }}
  cronus_password: {{ printf "%s/%s/%s/keystone-user/campfire/password" $vbase $region .Release.Namespace | b64enc }}
