kind: Service
apiVersion: v1

metadata:
  name: campfire
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/targets: openstack

spec:
  selector:
    name: campfire
  ports:
    - name: campfire
      port: 80
      protocol: TCP
