apiVersion: v1
kind: Secret

metadata:
  name: logs-query-exporter-secrets

data:
  username: {{ .Values.global.prom_user | b64enc | quote }}
  password: {{ .Values.global.prom_password | b64enc | quote }}
  failover_username: {{ .Values.global.prom_user_failover | b64enc | quote }}
  failover_password: {{ .Values.global.prom_password_failover | b64enc | quote }}
