kubernikus:
  imageTag: 6d53f8e0b70dd891332ca2b729de5741bc1418d8
  image: keppel.global.cloud.sap/ccloud/kubernikus

  #use a dedicated serviceaccount and proper RBAC rules for this deployment
  standalone: false
  useServiceAccount: true
  includeRBAC: true
  k8sniff:
    useRBAC: true

  api:
    policyFile: /etc/kubernikus/policy-ccadmin.json
  operator:
    nodeAffinity: false
    controllers: [groundctl, deorbiter, migration, servicing, certs]
  ingress:
    annotations:
      disco: "true"
kubernikus-dex:
  namespaceOverride: kubernikus

owner-info:
  support-group: containers
  service: kubernikus
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/kubernikus-metal
