apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-state-metrics-remote.fullname" . }}-kube-state-metrics
  labels:
    app.kubernetes.io/component: exporter
  {{- include "kube-state-metrics-remote.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kubeStateMetrics.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
    {{- include "kube-state-metrics-remote.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: kube-state-metrics
        app.kubernetes.io/version: 2.15.0
      {{- include "kube-state-metrics-remote.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.kubeStateMetrics.kubeStateMetrics.image.repository }}:{{ .Values.kubeStateMetrics.kubeStateMetrics.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /livez
            port: http-metrics
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: kube-state-metrics
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 8081
          name: telemetry
        readinessProbe:
          httpGet:
            path: /readyz
            port: telemetry
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources: {}
        securityContext: {{- toYaml .Values.kubeStateMetrics.kubeStateMetrics.containerSecurityContext
          | nindent 10 }}
      nodeSelector: {{- toYaml .Values.kubeStateMetrics.nodeSelector | nindent 8 }}
      serviceAccountName: {{ include "kube-state-metrics-remote.fullname" . }}-kube-state-metrics
