apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: {{ .Values.prometheusName }}
  name: {{ include "kube-state-metrics-remote.fullname" . }}
spec:
  groups:
    - name: {{ include "kube-state-metrics-remote.fullname" . }}.rules
      rules:
        - alert: ArgoraUpdateInError
          annotations:
            summary: Update CR in Error state.
            description: Argora Update CR status is in Error state for more than 1 minute.
          expr: >
            kube_customresource_status_state{customresource_kind="Update",customresource_group="argora.cloud.sap",state=~"Error"}
            == 1
          for: 1m
          labels:
            cluster: {{ .Values.clusterName | quote }}
            service: {{ include "kube-state-metrics-remote.fullname" . }}
            severity: warning
