apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: shoot
  name: {{ include "kube-state-metrics-remote.fullname" . }}
spec:
  groups:
    - name: {{ include "kube-state-metrics-remote.fullname" . }}.rules
      rules:
        - alert: ArgoraUpdateInError
          annotations:
            description: Argora Update CR status is in Error state for more than 1 minute.
          expr: |
            kube_customresource_status_state{customresource_kind="Update",customresource_group="argora.cloud.sap",state=~"Error"} == 1
          for: 1m
          labels:
            service: {{ include "kube-state-metrics-remote.fullname" . }}
            severity: warning
