apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: {{ .Values.name }}
  name: {{ include "kube-state-metrics-remote.fullname" . }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      scheme: http
      targetPort: {{ with index .Values.kubeStateMetrics.ports 0 }}{{ .port }}{{ end }}
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-state-metrics-remote.fullname" . }}
