apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/sapcc/argora//config/manager
- https://github.com/sapcc/argora//config/configmap
- https://github.com/sapcc/argora//config/secret
- https://raw.githubusercontent.com/sapcc/argora/refs/heads/main/config/rbac/service_account.yaml
- https://raw.githubusercontent.com/sapcc/argora/refs/heads/main/config/rbac/leader_election_role.yaml
- https://raw.githubusercontent.com/sapcc/argora/refs/heads/main/config/rbac/leader_election_role_binding.yaml
patches:
- path: kustomize/argora-operator-remote/manager-remote-patch.yaml
