apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argora-operator-remote.fullname" . }}-config
  labels:
  {{- include "argora-operator-remote.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.config.configJson | quote }}
