apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argora-operator-remote.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "argora-operator-remote.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  strategy:
    type: {{ .Values.controllerManager.strategy.type | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: argora
      control-plane: controller-manager
    {{- include "argora-operator-remote.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argora
        control-plane: controller-manager
      {{- include "argora-operator-remote.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args: {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        command:
        - /manager
        env:
        - name: ENABLE_WEBHOOKS
          value: {{ quote .Values.controllerManager.manager.env.enableWebhooks }}
        - name: KUBERNETES_SERVICE_HOST
          value: {{ quote .Values.controllerManager.manager.env.kubernetesServiceHost }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 30081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 30081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: remote-kubeconfig
          readOnly: true
        - mountPath: /etc/config
          name: config-volume
          readOnly: true
        - mountPath: /etc/credentials
          name: secret-volume
          readOnly: true
      hostNetwork: true
      securityContext: {{- toYaml .Values.controllerManager.podSecurityContext | nindent
        8 }}
      serviceAccountName: default
      terminationGracePeriodSeconds: 10
      volumes:
      - name: remote-kubeconfig
        secret:
          items:
          - key: token
            path: token
          - key: bundle.crt
            path: ca.crt
          secretName: argora-operator-remote-kubeconfig
      - configMap:
          name: argora-operator-config
        name: config-volume
      - name: secret-volume
        secret:
          secretName: argora-operator-secret
