apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argora-operator-remote.fullname" . }}-secret
  labels:
  {{- include "argora-operator-remote.labels" . | nindent 4 }}
stringData:
  credentials.json: {{ required "secret.credentialsJson is required" .Values.secret.credentialsJson
    | quote }}
type: Opaque
