apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argora-operator-remote.fullname" . }}-controller-manager
  labels:
  {{- include "argora-operator-remote.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
