global:
  region: test-1
secret:
  metalKubeConfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: "REDACTED"
        server: https://api.test-1.metal.example.com:6443
      name: metal-test-1
    contexts:
    - context:
        cluster: metal-test-1
        user: metal-user
      name: metal-test-1-context
    current-context: metal-test-1-context
    kind: Config
    preferences: {}
    users:
    - name: metal-user
      user:
        client-certificate-data: "REDACTED"
        client-key-data: "REDACTED"
