apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "netapp-credential-rotator.labels" . | nindent 4 }}
  name: {{ include "netapp-credential-rotator.serviceAccountName" . }}-manager-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "netapp-credential-rotator.serviceAccountName" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "netapp-credential-rotator.serviceAccountName" . }}
