kubeStateMetrics:
  kubeStateMetrics:
    args:
      - --port=:30080
      - --telemetry-port=30081
      - --custom-resource-state-config-file=/etc/config/custom-resource-state.yaml
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      seccompProfile:
        type: RuntimeDefault
    env:
      enableWebhooks: "false"
      kubernetesServiceHost: apiserver-url
    image:
      repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
      tag: v2.15.0
  nodeSelector:
    kubernetes.io/os: linux
  ports:
  - name: http-metrics
    port: 30080
    targetPort: http-metrics
  - name: telemetry
    port: 30081
    targetPort: telemetry
  replicas: 1
  serviceAccount:
    annotations: {}
  strategy:
    type: Recreate
  type: ClusterIP
kubernetesClusterDomain: cluster.local
config:
  customResourceStateYaml: ""
fullnameOverride: kube-state-metrics-remote
