controllerManager:
  manager:
    args:
      - --health-probe-bind-address=:30081
      - --metrics-bind-address=127.0.0.1:30082
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    env:
      enableWebhooks: "false"
      kubernetesServiceHost: apiserver-url
    image:
      repository: controller
      tag: 1133b6d2dd30ae6f1335b2fe5570d99b6c491410
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
kubernetesClusterDomain: cluster.local
fullnameOverride: argora-operator
