global:
  keystoneNamespace: keystone
  region: xx-yy-1
  tld: example.org
  registry: registry.example.com
  quayIoMirror: registry.example.com/quayio
  vaultBaseURL: vault.example.com/secrets
  domain_seeds:
    customer_domains: [ bar, foo ]

campfire:
  central_region: xx-yy-2
  all_regions: [ xx-yy-1, xx-yy-2 ]
  mail_type:
    expire: 
      subject: "expire subject"
      condition: "expire"
    confirm:
      subject: "confirm subject"
      condition: "be confirmed"
  

limes:
  image_tag: '19700101000000'

  clusters:
    ccloud:
      catalog_url: https://limes-3.example.com

  passwords:
    ccloud:
      os_password: abc
      rabbitmq_password: def
