apiVersion: v1
kind: Service
metadata:
  name: boot-http
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: boot
    port: {{ .Values.ipxe.port }}
    protocol: TCP
    targetPort: {{ .Values.ipxe.port }}
  selector:
    app.kubernetes.io/instance: boot-operator
  type: ClusterIP
