owner-info:
  support-group: containers
  service: nodeCIDRcontroller
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/nodecidr-controller
  maintainers:
    - Alexandru Mihai
    - Dmitri Fedotov
    - Goeran Gudat
    - Marian Schwarz
image:
  repository: sapcc/ccloud-nodecidr-controller
  tag:

netbox: {}
  #apiToken:
