apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-token-rotate
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metal-token-rotate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metal-token-rotate
subjects:
- kind: ServiceAccount
  name: metal-token-rotate
  namespace: garden
