apiVersion: v1
kind: Secret
metadata:
  name: maillog-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: maillog
type: Opaque
data:
  STORAGE_PASSWORD: {{ .Values.storage.password | b64enc}}
  {{- if and .Values.storage.failoverUser .Values.storage.failoverUser.password }}
  STORAGE_FAILOVER_PASSWORD: {{  .Values.storage.failoverUser.password | b64enc}}
  {{- end }}
  KEYSTONE_PASSWORD: {{ .Values.keystone.password | b64enc}}
  {{- if or .Values.tls.clientCertOU .Values.global.clientCertOU }}
  CLIENT_CERT_OU: {{ .Values.tls.clientCertOU | default .Values.global.clientCertOU | b64enc}}
  {{- end }}
