apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "controlplane-kubeadm.fullname" . }}-serving-cert
  labels:
  {{- include "controlplane-kubeadm.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "controlplane-kubeadm.fullname" . }}-{{ .Release.Namespace }}-kubeadm-control-plane-webhook-service.{{
    .Release.Namespace }}-kubeadm-control-plane-system.svc'
  - '{{ include "controlplane-kubeadm.fullname" . }}-{{ .Release.Namespace }}-kubeadm-control-plane-webhook-service.{{
    .Release.Namespace }}-kubeadm-control-plane-system.svc.{{ .Values.kubernetesClusterDomain
    }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "controlplane-kubeadm.fullname" . }}-selfsigned-issuer'
  secretName: capi-kubeadm-control-plane-webhook-service-cert
  subject:
    organizations:
    - k8s-sig-cluster-lifecycle
