{{- if and .Values.pluginPreset.enabled .Values.controlplaneOperations.enabled }}
apiVersion: greenhouse.sap/v1alpha1
kind: PluginPreset
metadata:
  name: controlplane-operations
  namespace: {{ .Release.Namespace }}
spec:
  clusterSelector:
    matchLabels:
      greenhouse.sap/cluster-presets-enabled: "true"
      cluster-type: "controlplane"
  plugin:
    pluginDefinition: contolplane-operations
    releaseNamespace: contolplane-operations
    optionValues:
      - name: prometheusRules.ruleSelectors
        value:
          - name: plugin
            value: 'kube-monitoring-{{ "{{ .Values.global.greenhouse.clusterName }}" }}'
      - name: prometheusRules.additionalRuleLabels
        value:
          service: cc-cp
          support_group: containers
{{- end -}}
