apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
  namespace: netapp-credential-rotator
data:
  vault_addr: {{ .Values.vault.addr | b64enc | quote }}
  vault_role_id: {{ .Values.vault.approle.roleId | include "resolve_secret" }}
  vault_secret_id: {{ .Values.vault.approle.secretId | include "resolve_secret" }}
