global:
  is_global_region: false
  domain_seeds:
    customer_domains: []
    customer_domains_without_support_projects: []

owner-info:
  support-group: containers
  service: billing
  maintainers:
    - Stefan Majewsky
    - Sandro Jäckel
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/openstack/billing
