---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metal-token-rotate
  namespace: garden
{{- if .Values.targetSecret }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-token-rotate
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - {{ (split "/" .Values.targetSecret)._1 | quote }}
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metal-token-rotate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metal-token-rotate
subjects:
- kind: ServiceAccount
  name: metal-token-rotate
  namespace: garden
{{- else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-token-rotate
rules:
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - tokenreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metal-token-rotate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metal-token-rotate
subjects:
- kind: ServiceAccount
  name: metal-token-rotate
  namespace: garden
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metal-token-rotate
  namespace: {{ .Values.config.serviceAccountNamespace | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  resourceNames:
  - {{ .Values.config.serviceAccountName | quote }}
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metal-token-rotate
  namespace: {{ .Values.config.serviceAccountNamespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metal-token-rotate
subjects:
- kind: ServiceAccount
  name: metal-token-rotate
  namespace: garden
{{- end }}
