apiVersion: v1
kind: Secret
metadata:
  name: metal-token-rotate-garden-token
  labels:
    resources.gardener.cloud/purpose: token-requestor
    resources.gardener.cloud/class: shoot
  annotations:
    serviceaccount.resources.gardener.cloud/name: metal-token-rotate
    serviceaccount.resources.gardener.cloud/namespace: garden
# data:
#  token: will be populated by the gardener-resource-manager
