{{- if .Values.envoy_external }}
{{- range $az := .Values.global.availability_zones }}
kind: Deployment
apiVersion: apps/v1

metadata:
  name: swift-envoy-{{ $.Values.cluster_name }}-{{ $az }}
  labels:
    release: "{{ $.Release.Name }}"
    os-cluster: {{ $.Values.cluster_name }}
spec:
  revisionHistoryLimit: 5
  {{- $replicas_az := 0.0 }}
  {{- if $.Values.envoy_external }}
  {{- $replicas_az = default 2.0 (index $.Values (printf "envoy_deployment_replicas_%s" $az)) }}
  {{- end }}
  replicas: {{ $replicas_az }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- if eq $replicas_az 1.0 }}
      maxUnavailable: 0
      {{- else }}
      maxUnavailable: 1
      {{- end }}
      maxSurge: 2
  selector:
    matchLabels:
      component: swift-envoy-{{ $.Values.cluster_name }}
  template:
    metadata:
      labels:
        component: swift-envoy-{{ $.Values.cluster_name }}
        alert-tier: os
        alert-service: swift
        from: deployment
        os-cluster: {{ $.Values.cluster_name }}
        for-service: swift-proxy-{{ $.Values.cluster_name }}
      annotations:
        checksum/envoy.bin: {{ include "swift/templates/envoy-bin-configmap.yaml" $ | sha256sum }}
        checksum/envoy-cluster.etc: {{ include "swift/templates/etc/envoy-cluster-configmap.yaml" $ | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/targets: {{ required ".Values.alerts.prometheus.openstack missing" $.Values.alerts.prometheus.openstack }}
    spec:
      # No tolerations for swift nodes
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: {{ $az }}
      affinity:
        podAntiAffinity:
          # Prefere to be scheduled on nodes not yet running this proxy from a deplyoment
          # kubernetes.io/hostname legacy control plane
          # kubernetes.cloud.sap/host aPod bases control plane
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - swift-envoy-{{ $.Values.cluster_name }}
                - key: from
                  operator: In
                  values:
                  - deployment
              topologyKey: "kubernetes.io/hostname"
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - swift-envoy-{{ $.Values.cluster_name }}
                - key: from
                  operator: In
                  values:
                  - deployment
              topologyKey: "kubernetes.cloud.sap/host"
      volumes:
        - name: tls-secret
          secret:
            secretName: tls-swift-{{ $.Values.cluster_name }}
        - name: envoy-bin
          configMap:
            name: envoy-bin
        - name: envoy-etc-cluster
          configMap:
            name: envoy-etc-{{ $.Values.cluster_name }}
      containers:
        - name: envoy
          image: {{ $.Values.global.registryAlternateRegion }}/swift-envoy:{{ default $.Values.image_version_envoy "v1.17.1-20210317124712" }}
          command:
            - /usr/bin/dumb-init
          args:
            - /bin/sh
            - /envoy-bin/envoy-start
          env:
            - name: DEBUG_CONTAINER
              value: "false"
          # TODO: securityContext: { runAsNonRoot: true }
          resources:
            requests:
              cpu: "1000m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /tls-secret
              name: tls-secret
            - mountPath: /envoy-bin
              name: envoy-bin
            - mountPath: /envoy-etc-cluster
              name: envoy-etc-cluster
          livenessProbe:
            httpGet:
              path: /ready
              port: 9901
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{ $.Values.proxy_public_port }}
              scheme: HTTPS
              httpHeaders:
                - name: Host
                  value: {{ include "swift_endpoint_host" $ }}
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
          ports:
            - name: metrics
              containerPort: 9902

---
{{- end }}
{{- end }}
